### ISSUE TITLE
不知道是什么问题

### ISSUE THREAD

**Issue by devtip** [abersheeran/websocks#2]
Server端跟Client端都弄好了。。。依然访问不成功。。。我建议出一个视频。。。你觉得怎么样？

**Comment by abersheeran** [comment]
具体是什么报错，你不截图出来我又怎么知道呢？

**Comment by devtip** [comment]
> 具体是什么报错，你不截图出来我又怎么知道呢？

服务端和客户端均采用docker部署的方式，服务端部署在阿里云上，客户端在我电脑上。。。均没有报错，电脑上连sock5 127.0.0.1 3128连不上。。。

**Comment by abersheeran** [comment]
我明白了，client 默认是监听的本地回环地址。我之前给出的 docker-compose 配置里没有显式的指定监听 0.0.0.0，所以没法映射出去。

```
version: '3.3'
services:
  websocks:
    image: abersheeran/websocks
    command: websocks client -S USERNAME:PASSWORD@HOST:PORT 0.0.0.0 3128
    ports:
      - "3128:3128"
    restart: always
```

你改一下客户端的 docker-compose.yml 到上面这个试试。
